<?php

namespace App\Http\Controllers;

use App\Models\Notification;
use App\Models\Child;
use App\Models\VaccineInventory;
use App\Services\NotificationService;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    protected $notificationService;

    public function __construct(NotificationService $notificationService)
    {
        $this->notificationService = $notificationService;
    }

    /**
     * Display the notification center
     */
    public function index()
    {
        // Fetch notifications from database (already generated by observers and cron)
        // PostgreSQL compatible ordering using CASE
        $notifications = Notification::with(['child.guardian', 'inventory.vaccine'])
            ->orderByRaw("CASE 
                WHEN notif_notification_type = 'overdue' THEN 1 
                WHEN notif_notification_type = 'inventory' THEN 2 
                WHEN notif_notification_type = 'upcoming' THEN 3 
                ELSE 4 
            END")
            ->orderBy('notif_is_read', 'asc')
            ->orderBy('created_at', 'desc')
            ->get();

        // Calculate counts for the tab pills
        $counts = [
            'all' => $notifications->count(),
            'overdue' => $notifications->where('notif_notification_type', 'overdue')->count(),
            'upcoming' => $notifications->where('notif_notification_type', 'upcoming')->count(),
            'inventory' => $notifications->where('notif_notification_type', 'inventory')->count(),
        ];

        // Transform database records to match the view format
        $notifications = $notifications->map(function ($notif) {
            return (object)[
                'id' => $notif->notif_id,
                'type' => $notif->notif_notification_type,
                'message' => $notif->notif_message,
                'is_read' => $notif->notif_is_read,
                'created_at' => $notif->created_at,
                'child_id' => $notif->notif_child_id,
                'child_name' => $notif->child ? $notif->child->getFullNameAttribute() : null,
                'inventory_id' => $notif->notif_inventory_id,
                'batch_number' => $notif->inventory ? $notif->inventory->inv_batch_number : null,
                'quantity' => $notif->inventory ? $notif->inventory->inv_quantity_available : null,
                'expiry_date' => $notif->inventory ? $notif->inventory->inv_expiry_date : null,
                'vaccine_name' => $this->extractVaccineName($notif->notif_message),
                'dose_number' => $this->extractDoseNumber($notif->notif_message),
            ];
        });

        return view('notifications.index', compact('notifications', 'counts'));
    }

    /**
     * Extract vaccine name from notification message
     */
    private function extractVaccineName($message)
    {
        // Extract text between "for" and "(Dose" or just after "for"
        if (preg_match('/for\s+(.+?)\s+\(Dose/i', $message, $matches)) {
            return trim($matches[1]);
        }
        if (preg_match('/for\s+(.+?)\s+in\s+\d+/i', $message, $matches)) {
            return trim($matches[1]);
        }
        return 'Vaccination';
    }

    /**
     * Extract dose number from notification message
     */
    private function extractDoseNumber($message)
    {
        if (preg_match('/Dose\s+(\d+)/i', $message, $matches)) {
            return (int)$matches[1];
        }
        return 1;
    }

    /**
     * Mark a single notification as read
     */
    public function markAsRead($id)
    {
        $notification = Notification::findOrFail($id);
        $notification->update(['notif_is_read' => true]);

        return back()->with('success', 'Notification marked as read.');
    }

    /**
     * Mark all notifications as read
     */
    public function markAllAsRead()
    {
        Notification::where('notif_is_read', false)
            ->update(['notif_is_read' => true]);

        return back()->with('success', 'All notifications marked as read.');
    }

    /**
     * Dismiss/soft delete a notification
     */
    public function destroy($id)
    {
        $notification = Notification::findOrFail($id);
        $notification->delete(); // Soft delete

        return back()->with('success', 'Notification dismissed.');
    }

    /**
     * Get notification count for navbar badge
     */
    public function getUnreadCount()
    {
        $criticalCount = Notification::where('notif_is_read', false)
            ->where(function ($query) {
                $query->where('notif_notification_type', 'overdue')
                      ->orWhere(function ($q) {
                          $q->where('notif_notification_type', 'inventory')
                            ->where(function ($subQ) {
                                $subQ->where('notif_message', 'LIKE', 'EXPIRED%')
                                     ->orWhere('notif_message', 'LIKE', 'CRITICAL%');
                            });
                      });
            })
            ->count();

        return response()->json(['count' => $criticalCount]);
    }

    /**
     * Manual trigger to regenerate all notifications (for testing/admin)
     */
    public function regenerateAll()
    {
        $this->notificationService->generateAllChildVaccineNotifications();
        $this->notificationService->generateAllInventoryNotifications();

        return back()->with('success', 'All notifications regenerated successfully.');
    }
}